Newspaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),  # new
    path('users/', include('django.contrib.auth.urls')),  # new
    path('jobs/', include('jobs.urls')),  # new
    path('bids/', include('bids.urls')),  # new

    path('', TemplateView.as_view(template_name='home.html'),
         name='home'),
    path('pages/', include('pages.urls')),  # new

]

bids/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [

    path('', views.home, name='home'),

    path('marketplace/', views.placements, name='placements'),
    path('marketplace/<placement_slug>/', views.placement_detail, name='placement-detail'),

    path('my-bids/', views.bid_summary, name='bid-summary'),
    path('confirm-bids/', views.confirm_bids, name='confirm-bids'),

    path('about/', views.about, name='about')
]

templates/about.html
{% extends 'base.html' %}
{% block content %}

<section class="section">
    <section class="container">

        <article class="card">
            <div class="card-content">
                <h4>About</h4>
                <p class="custom-font-1">This application was built as a side project, in order to learn how to design and build a bidding system from scratch. The theme is based on capital raising for companies. It includes an auth system, marketplace, companies, placements,
                    dashboard, mobile friendly design. I used Django mainly, to develop this application.</p>
</div>
        </article>
        <article class="card">
            <div class="card-content">
                <h4>Available Routes</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item"><span class="chip">/</span> The home page. Contains news.</li>
                    <li class="collection-item"><span class="chip">about/</span> Holds details about the application.</li>
                    <li class="collection-item"><span class="chip">register/</span> Allows users to register an account</li>
                    <li class="collection-item"><span class="chip">login/</span> Allows users to login to an account</li>
                    <li class="collection-item"><span class="chip">logout/</span> Allows users to logout and clear their session</li>

                    <li class="collection-item"><span class="chip">marketplace/</span> Listing of placements from various companies.</li>

                    <li class="collection-item"><span class="chip">marketplace/slug/</slug></span> Detailed view for a placement within the marketplace.</li>
                    <li class="collection-item"><span class="chip">my-bids/</span> User scope bid summary for available placements.</li>
                    <li class="collection-item"><span class="chip">dashboard/</span> Basic analytics and animated charts for the database.</li>

                </ul>
            </div>
        </article>


        <article class="card">
            <div class="card-content">
                <h4>Features and specs</h4>
                <ul class="collection custom-font-1">
                    <li class="collection-item">Authentication system - users can login, register and logout, passwords are securely hashed with PBKDF2 method.</li>
                    <li class="collection-item ">Certain routes are protected with a login required decorator, giving security to administrators/owners. Unregistered users are prompted to login on the home page.</li>
                    <li class="collection-item">Dashboard include dynamic and animated charts to draw insights from database.</li>
                    <li class="collection-item">Data is modelled in ORM and automatically generated by Django to RDBS of choice.</li>
                    <li class="collection-item">Data included in application is randomly generated using the <code>faker</code> library</li>
                    <li class="collection-item">App uses materialize css framework borrowing from Google's material design principles</li>
                    <li class="collection-item">App developed mainly in Django framework and Javascript.</li>
                </ul>
            </div>
        </article>

    </section>
</section>

{% include 'footer.html' %} {% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}FIX App{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'home' %}">FIX</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item"
              href="{% url 'password_change'%}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">
              Log Out</a>
            </div>
          </li>
        </ul>
      {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'login' %}" class="btn btn-outline-secondary">
          Log In</a>
          <a href="{% url 'signup' %}" class="btn btn-primary ml-2">
          Sign up</a>
        </form>
      {% endif %}
    </div>
  </nav>
  <main>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/bid-summary.html
{% extends 'base.html' %}

{% block content %}

<section class="section">
    <section class="container">
        <div class="card">
            <div class="card-content">
                <h4>Your bid summary</h4>
                <table class="table responsive-table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Bid status</th>
                            <th>Company Name</th>
                            <th>Timestamp</th>
                            <th>$ Bidded</th>
                            <th>no. Shares</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for b in bids %}
                            <tr>
                                <td>{{ b.id }}</td>
                                <td>{% if b.confirmed %}<span class="chip">Confirmed</span>{%else%} <span class="chip indigo darken-2 white-text">Unconfirmed</span>       {%endif%}</td>
                                <td>{{ b.placement.placement_company }}</td>
                                <td>{{ b.placementbid_created }}</td>
                                <td>{{ b.offer}}</td>
                                <td>{{ b.shares}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

                <a href="{% url 'app:confirm-bids' %}" style="margin-top: 1rem;" class="btn waves-light waves-effect pink">Confirm Bids</a>
            </div>
        </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/client_listings.html
{% extends 'base.html' %}
{% block title %}Jobs_Listings{% endblock title %}
{% block content %}
    <nav class="navbar navbar-light bg-light">
    #search through categories and locations
  <li class="nav-item"><a href="{% url 'job_new' %}">+ New</a></li>

  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>
    {% for job in object_list %}
    <div class="card">
   <div class="card-header">
     <span class="font-weight-bold">{{ job.title }}</span> &middot;
       <span class="text-muted">by {{ job.author }} |
           {{ job.date }}</span>
</div>
    <div class="card-body">
{{ job.body }}
</div>
    <div class="card-footer text-center text-muted">
        <a href="{% url 'job_edit' job.pk %}"><button>Edit</button></a> |
        <a href="{% url 'job_delete' job.pk %}"><button>Delete</button></a>
</div>
    </div>
<br />
{% endfor %}
{% endblock content %}

templates/footer.html
<footer class="page-footer indigo darken-2">
        <div class="container">
          <div class="row">
            <div class="col l4 s12">
              <h5 class="white-text">Anim eiusmod tempor.</h5>
              <p class="grey-text text-lighten-4 class="custom-font-1"">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius ea deserunt ipsa harum, sint commodi sed reprehenderit dolor cupiditate distinctio dolores a minus repudiandae quibusdam facere. Reprehenderit itaque sequi deserunt.</p>
            </div>

            <div class="col l4 offset-l4 s12">
              <h5 class="white-text">Routes</h5>
              <ul  class="custom-font-1">
                <li><a class="grey-text text-lighten-3" href="#!">Home</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Marketplace</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Latest News</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Legal</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Terms & Conditions</a></li>
                <li><a class="grey-text text-lighten-3" href="#!">Careers</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="footer-copyright pink lighten-1">
          <div class="container center custom-font-1">
          © 2019 Copyright Text

          </div>
        </div>
      </footer>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
{% if user.is_authenticated %}

Hi fundi {{ user.username }} welcome to  Fixit!
    <h2>New jobs available</h2>
    <p><a href="{% url 'job_list' %}">view Job MarketPlace</a></p>


<p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}

  <div class="card z-depth-2">
            <div class="card-content">
                <h5>Notice</h5>
                <p class="custom-font-1">You must have a registered account and be logged in, in order to view and place bids within our marketplace.</p>
            </div>
        </div><a href="{% url 'login' %}">Log In</a> |
<a href="{% url 'signup' %}">Sign Up</a>
{% endif %}
 {% include 'footer.html' %} {% endblock content %}

templates/job_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete</h1>
<form action="" method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ job.title }}"?</p>
<button class="btn btn-danger ml-2" type="submit">Confirm</button>
</form>
{% endblock content %}

templates/job_detail.html
{% extends 'base.html' %}
{% block title %}Jobs_Details{% endblock title %}
{% block content %}
    <nav class="navbar navbar-light bg-light">

</nav>
    {% for job in object_list %}
    <div class="card">
   <div class="card-header">
     <span class="font-weight-bold">Job Type:{{ job.title }}</span> &middot;
      <div class="card-body">
 client:{{ job.client }}
</div>
         <div class="card-body">
 category:{{ job.category }}
</div>
            <div class="card-body">
 location:{{ job.location }}
</div>
            <div class="card-body">
 Date Added:{{ job.date }}
</div>

</div>
    <div class="card-body">
Description:{{ job.body }}
</div>
    </div>
  <div class="card">
           <div class="card-content">
               <form action="" method="POST" class="form">
                   {% csrf_token %}
               <h5>Promote Bid</h5>
               <label for="">
                   Share Quantity
               </label>
               <input name="quantity" required id="quantity" type="number" min=1>
               <label for="">
                   Amount ($)
               </label>
               <input name="amount" required id="amount" type="number" min=1>
               <button type="submit" style="margin-top: 1rem;" class="btn btn-primary" >Submit Bid</button>
            </form>
           </div>
       </div>
<br />
{% endfor %}
{% endblock content %}

templates/job_edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Edit</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<button class="btn btn-info ml-2" type="submit">Update</button>
</form>
{% endblock content %}

templates/job_list.html
{% extends 'base.html' %}
{% block title %}Jobs_Listings{% endblock title %}
{% block content %}





    <nav class="navbar navbar-light bg-light">
    #search through categories and locations
        <div></div>

  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>

       <div class="card">
                <div class="card-content">
                        <table class="table responsive-table">
                                <thead>
                                    <tr>

                                        <th>Job_Title</th>
                                        <th>client</th>
                                        <th>Category</th>
                                        <th>Added</th>
                                        <th>View Details</th>
                                    </tr>
                                </thead>

                                <tbody>
    {% for job in object_list %}
        <td><span class="chip indigo white-text">{{ job.title }}</span></td>
        <td>{{ job.client }}</td>
        <td>{{ job.category }}</td>
        <td>{{ job.date }}</td>

        <td><a href="{% url 'job_detail' %}" style="margin-top: 1rem;" class="btn pink waves-effect waves-light">View Details</a></td>
        </tr>
<br/>
{% endfor %}
         </tbody>
                            </table>
{#        {% include 'footer.html' %}#}

                {% endblock content %}

templates/job_new.html
{% extends 'base.html' %}
{% block content %}
<h1>Add new Job listing:</h1>
<form action="" method="post">{% csrf_token %}
{{ form.as_p }}
<button class="btn btn-success ml-2" type="submit">Save</button>
</form>
    {% include 'footer.html' %}{% endblock content %}

templates/placements.html
{% extends 'base.html' %}

{% block content %}


{% load static %}

<section class="section">
    <section class="container">

            <div class="col s12">
                    <div class="card">
                            <div class="card-content">
                                <h4>Welcome to the marketplace</h4>
                                <p>Explore placements by various listed companies</p>
                                <img src="{% static 'ishant-mishra-1349434-unsplash.jpg' %}" alt="" class="responsive-img fade-in">
                            </div>
                        </div>
            </div>

            <div class="card">
                <div class="card-content">
                        <table class="table responsive-table">
                                <thead>
                                    <tr>

                                        <th>Placement Desc</th>
                                        <th>Company</th>
                                        <th>Added</th>
                                        <th>Modified</th>
                                        <th>View Details</th>
                                    </tr>
                                </thead>

                                <tbody>
                                        {%for p in placements %}
                                        <tr>

                                            <td>{{ p.placement_title }}</td>
                                            <td><span class="chip indigo white-text">{{ p.placement_company }}</span></td>
                                            <td>{{ p.placement_created }}</td>
                                            <td>{{ p.placement_modified }}</td>
                                            <td><a href="{% url 'app:placement-detail' p.placement_slug %}" style="margin-top: 1rem;" class="btn pink waves-effect waves-light">View Details</a></td>
                                        </tr>
                                        {% endfor %}
                                </tbody>
                            </table>

                            <ul class="pagination center">
                                {% if placements.has_previous %}
                                <li class="waves-effect"><a href="?page={{placements.previous_page_number}}">{{ placements.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="active indigo"><a href="#!">{{placements.number}}</a></li>

                                {% if placements.has_next %}
                                <li class="waves-effect"><a href="?page={{placements.next_page_number}}">{{ placements.next_page_number}}</a></li>
                                {% endif %}
                            </ul>

                </div>
            </div>

    </section>
</section>

{% include 'footer.html' %}
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign Up{% endblock title%}

{% block content %}
  <h2>Sign Up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Sign Up</button>
  </form>
{% endblock content %}

templates/view_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Job_details</title>
</head>
<body>
{#Bid Job #}
{##bid status either accepted,canceled or pending#}
</body>
</html>
{% include 'footer.html' %}